const gulp = require("gulp");
const pug = require("gulp-pug");
const sass = require("gulp-sass")(require("sass"));
const postcss = require("gulp-postcss");
const autoprefixer = require("autoprefixer");
const cssnano = require("cssnano");
const concat = require("gulp-concat");
const uglify = require("gulp-uglify");
const imagemin = require("gulp-imagemin");
const webp = require("gulp-webp");
const svgSprite = require("gulp-svg-sprite");
const newer = require("gulp-newer");
const gulpif = require("gulp-if");
const plumber = require("gulp-plumber");
const notify = require("gulp-notify");
const rename = require("gulp-rename");
const del = require("del");
const fs = require("fs");
const path = require("path");
const browserSync = require("browser-sync").create();

const isProd = process.argv.includes("--production");
const isDev = !isProd;

// Пути
const paths = {
  src: {
    pug: "src/pug/**/*.pug",
    pugComponents: "src/pug/**/*.pug",
    scss: "src/scss/**/*.scss",
    scssComponents: "src/pug/**/*.scss",
    js: "src/js/**/*.js",
    jsLibs: "src/js/libs/**/*.js",
    fonts: "src/fonts/**/*",
    img: "src/img/**/*",
    icons: "src/img/svg/**/*.svg",
  },
  dist: {
    base: "dist/",
    css: "dist/css/",
    js: "dist/js/",
    fonts: "dist/fonts/",
    img: "dist/img/",
  },
  watch: {
    pug: "src/pug/**/*.pug",
    scss: "src/scss/**/*.scss",
    js: "src/js/**/*.js",
    fonts: "src/fonts/**/*",
    img: "src/img/**/*",
  },
};

// Обработка ошибок
const plumberNotify = (title) => {
  return plumber({
    errorHandler: notify.onError({
      title: title,
      message: "Error: <%= error.message %>",
    }),
  });
};

// Очистка dist
function cleanDist() {
  return del("dist/**/*");
}

// Сборка SCSS из компонентов
function collectComponentsScss() {
  return new Promise((resolve, reject) => {
    const componentsDir = "src/pug/components";
    const outputFile = "src/scss/_components.scss";

    // Проверяем существование папки компонентов
    if (!fs.existsSync(componentsDir)) {
      // Создаем пустой файл если папки нет
      fs.writeFileSync(
        outputFile,
        "// Auto-generated components styles\n",
        "utf8"
      );
      resolve();
      return;
    }

    let imports =
      "// Auto-generated components styles\n// DO NOT EDIT THIS FILE MANUALLY\n\n";

    // Рекурсивно ищем все SCSS файлы в компонентах
    function findScssFiles(dir) {
      const files = fs.readdirSync(dir);

      files.forEach((file) => {
        const filePath = path.join(dir, file);
        const stat = fs.statSync(filePath);

        if (stat.isDirectory()) {
          findScssFiles(filePath);
        } else if (file === "style.scss") {
          // Создаем относительный путь для импорта
          const relativePath = path
            .relative("src/scss", filePath)
            .replace(/\\/g, "/");
          imports += `@import '${relativePath}';\n`;
        }
      });
    }

    try {
      findScssFiles(componentsDir);
      fs.writeFileSync(outputFile, imports, "utf8");
      console.log("✅ Components SCSS collected successfully");
      resolve();
    } catch (error) {
      reject(error);
    }
  });
}

// Pug
function compilePug() {
  return gulp
    .src(["src/pug/*.pug", "!src/pug/_*.pug"])
    .pipe(plumberNotify("PUG"))
    .pipe(
      pug({
        pretty: isDev,
        basedir: "src/pug", // Для корректных путей в include
      })
    )
    .pipe(gulp.dest(paths.dist.base))
    .pipe(browserSync.stream());
}

// SCSS
function compileScss() {
  const plugins = [
    autoprefixer(),
    ...(isProd ? [cssnano()] : [])
  ];

  // Компилируем ТОЛЬКО main.scss, не все SCSS файлы подряд
  return gulp.src('src/scss/main.scss')
    .pipe(plumberNotify('SCSS'))
    .pipe(sass({
      includePaths: ['src/scss', 'src/pug/'],
      quietDeps: true
    }).on('error', sass.logError))
    .pipe(postcss(plugins))
    .pipe(rename({ suffix: '.min' }))
    .pipe(gulp.dest(paths.dist.css))
    .pipe(browserSync.stream());
}

// JavaScript
function compileJs() {
  // Main JS
  gulp
    .src(["src/js/main.js", "src/js/**/*.js", "!src/js/libs/**/*"])
    .pipe(plumberNotify("JS"))
    .pipe(concat("main.js"))
    .pipe(gulpif(isProd, uglify()))
    .pipe(gulp.dest(paths.dist.js))
    .pipe(browserSync.stream());

  // Libs JS
  return gulp
    .src(paths.src.jsLibs)
    .pipe(plumberNotify("JS Libs"))
    .pipe(concat("libs.min.js"))
    .pipe(uglify())
    .pipe(gulp.dest(paths.dist.js))
    .pipe(browserSync.stream());
}

// Шрифты
function copyFonts() {
  return gulp
    .src(paths.src.fonts)
    .pipe(newer(paths.dist.fonts))
    .pipe(gulp.dest(paths.dist.fonts))
    .pipe(browserSync.stream());
}

// SVG спрайт
function createSvgSprite() {
  return gulp
    .src(paths.src.icons)
    .pipe(plumberNotify("SVG"))
    .pipe(
      svgSprite({
        mode: {
          stack: {
            sprite: "../sprite.svg",
          },
        },
      })
    )
    .pipe(gulp.dest(paths.dist.img))
    .pipe(browserSync.stream());
}

// Изображения
function optimizeImages() {
  return gulp
    .src([paths.src.img, "!src/img/svg/**/*"])
    .pipe(newer(paths.dist.img))
    .pipe(gulpif(isProd, imagemin()))
    .pipe(gulp.dest(paths.dist.img))
    .pipe(browserSync.stream());
}

// WebP
function createWebp() {
  return gulp
    .src(["src/img/**/*.{jpg,png}", "!src/img/svg/**/*"])
    .pipe(
      newer({
        dest: paths.dist.img,
        ext: ".webp",
      })
    )
    .pipe(webp({ quality: 80 }))
    .pipe(gulp.dest(paths.dist.img))
    .pipe(browserSync.stream());
}

// Сервер
function server() {
  browserSync.init({
    server: {
      baseDir: paths.dist.base,
    },
    notify: false,
  });
}

// Наблюдение за изменениями
function watchFiles() {
  gulp.watch("src/pug/**/*.pug", compilePug);
  gulp.watch([
    'src/scss/**/*.scss',
    'src/pug/**/*.scss',
    '!**/*.min.scss', // ИСКЛЮЧАЕМ минифицированные файлы
    '!dist/**/*' // ИСКЛЮЧАЕМ папку dist
  ], compileScss);

  gulp.watch(paths.watch.js, compileJs);
  gulp.watch(paths.watch.fonts, copyFonts);
  gulp.watch(
    ["src/img/**/*", "!src/img/svg/**/*"],
    gulp.parallel(optimizeImages, createWebp)
  );
  gulp.watch(paths.src.icons, createSvgSprite);
}

// Сборки
const build = gulp.series(
  cleanDist,
  collectComponentsScss,
  gulp.parallel(
    compilePug,
    compileScss,
    compileJs,
    copyFonts,
    optimizeImages,
    createWebp,
    createSvgSprite
  )
);

const dev = gulp.series(build, gulp.parallel(watchFiles, server));

// Экспорт задач
exports.default = dev;
exports.build = build;
exports.clean = cleanDist;
exports.pug = compilePug;
exports.scss = compileScss;
exports.js = compileJs;
exports.fonts = copyFonts;
exports.images = gulp.parallel(optimizeImages, createWebp);
exports.sprite = createSvgSprite;
exports.collectScss = collectComponentsScss;
